import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]

    tutorialSidebar: [
        'index',
        {
            type: 'category',
            label: 'Installation',
            collapsed: false,
            items: [
                'installation/quick-start',
                'installation/env-variables',
                {
                    type: 'category',
                    label: 'Reverse Proxies',
                    items: [
                        'installation/reverse-proxies/nginx',
                        'installation/reverse-proxies/caddy',
                        'installation/reverse-proxies/try-cloudflare'
                    ]
                },
                {
                    type: 'category',
                    label: 'Node install',
                    items: ['installation/node/quick-start', 'installation/node/env-variables']
                }
            ]
        },
        {
            type: 'category',
            label: 'Subscription Templating',
            collapsed: false,
            items: ['subscription-templating/subscription-templates']
        },
        {
            type: 'category',
            label: 'Panel Overview',
            items: ['panel-overview/home']
        },
        {
            type: 'category',
            label: 'Migrating',
            items: ['migrating/marzban']
        },
        'donate'
    ]
}

export default sidebars
